# Personal information
title: Feng-Kai Huang
position: Ph.D. Student
affiliation: National Taiwan University
affiliation_link: https://www.csie.ntu.edu.tw/
email: leonelhuang@cmlab.csie.ntu.edu.tw
avatar: /assets/img/avatar.jpg
favicon: /assets/img/favicon-dark.png
google_scholar: https://scholar.google.com/citations?user=QlZ9PvYAAAAJ&hl=zh-TW
cv_link: /resume/general/main.pdf
linkedin: https://www.linkedin.com/in/leohuang0511/

# Search metadata
keywords: Feng-Kai Huang, Leonel Huang, computer vision, artificial intelligence
description: Feng-Kai (Leonel) Huang is a Ph.D. student at National Taiwan University working on artificial intelligence, computer vision, and multimedia processing.
url: https://leohuang0511.github.io

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - google_scholar_crawler/
  - resume/**/*.tex
  - resume/general/iiitv.png
